# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class St3llar < Formula
  desc ""
  homepage "https://github.com/v3nooonn/st3llar/tree/main/st3llar"
  version "0.0.2"
  depends_on :macos

  url "https://github.com/v3nooonn/st3llar/releases/download/v0.0.2/st3llar_Darwin_all.tar.gz"
  sha256 "c986fc10baf007491b7dc49caee86ce4c6f16429ae5ace21f62b1359320d7f97"

  def install
    bin.install "st3llar"
  end
end
